import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Navegacion from '../components/Navbar'
import Carta from '../components/Card'




export default function Home() {
  return (
<div className={styles.container}>
    <Head> 
        <title>Teclados y Arcane</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> 
        <link rel="stylesheet" href="globals.css" />
    </Head>
    
  <body>
    
      <Navegacion/>
      <Carta/>
      <h1>Rellenar este formulario para ingresar al Evento Arcane</h1>
    <form className='formulario'>

    <label for="nombre">Nombre Completo:</label>
    <input type="text" id="nombre" name="nombre" required autofocus/><br></br>
    <br></br>

    <label for="nombre">DNI :</label>
    <input type="text" id="nombre" name="nombre" required autofocus/><br></br>
    <br></br>

     <label for="email">Correo electrónico:</label>
     <input type="email" id="email" name="email" required/><br></br>
     <br></br>

     <label for="Password">Contraseña:</label>
    <input type="password" id="Password" name="Password"></input><br></br>
    <br></br>

     <label for="confirmPassword">Confirmar Contraseña:</label>
     <input type="password" id="confirmPassword" name="confirmPassword"></input><br></br>
     <br></br>

     <label for="fecha" >Fecha de Nacimiento:</label>
     <input type="date" id="fecha" name="fecha" required/><br></br>
     <br></br>
     
     <label for="numero">Cantidad de tickets que desee comprar:</label>
    <input type="number" id="numero" name="numero" min="-10" max="10"/><br></br>
    <br></br>

    <label for="telefono">Numero De Tarjeta:</label>
    <input type="tel" id="telefono" name="telefono" required/><br></br>
    <br></br>

    <label for="telefono">Numero De Telefono:</label>
    <input type="tel" id="telefono" name="telefono" required/><br></br>
    <br></br>

    <label for="nombre">Nombre Tutor/ en caso de ser menor de edad:</label>
    <input type="text" id="nombre" name="nombre" required autofocus/><br></br>
    <br></br>

    <label for="nombre">DNI tutor:</label>
    <input type="text" id="nombre" name="nombre" required autofocus/><br></br>
    <br></br>


    </form>
    
  </body>
</div>

  )
}
